#!/bin/sh

bold=$(tput bold)
reset=$(tput sgr0)

if [ "$1" = "clean" ]; then
  echo "${bold}Cleaning...${reset}"
  rm -r build bin

elif [ "$1" = "make" ]; then
  mkdir -p build
  cd build
  cmake ..
  make

elif [ "$1" = "train" ]; then
  ./bin/t5 train ./db/female/ ./db/male/
  
elif [ "$1" = "lbp" ]; then
  ./bin/t5 lbp "$2" 

elif [ "$1" = "test" ]; then
  ./bin/t5 test "$2" 

elif [ "$1" = "complete-test" ]; then
  echo "${bold}Male Test${reset}"
  for i in ./db/male/*.jpg; do
    result="$(./bin/t5 test ${i})"
    printf "Imagen %s: %s\n" "${i}" "${result}"
  done
  
  echo "${bold}Female Test${reset}"
  for i in ./db/female/*.jpg; do
    result="$(./bin/t5 test ${i})"
    printf "Imagen %s: %s\n" "${i}" "${result}"
  done


else
  echo "Uso: $./t5 make|clean|train|test|lbp|complete-test"
fi

