#!/bin/sh

bold=$(tput bold)
reset=$(tput sgr0)

if [ "$1" = "clean" ]; then
  echo "${bold}Cleaning...${reset}"
  rm -r build bin

elif [ "$1" = "make" ]; then
  mkdir -p build
  cd build
  cmake ..
  make

elif [ "$1" = "test" ]; then
  ./bin/t4 ./db/0024.jpg ./db/0024.bmp 
  
elif [ "$1" = "plot" ]; then
  python src/plot_complete.py ./db

elif [ "$1" = "roc" ]; then
  for i in ./db/*.jpg; do
    ./bin/t4 $i ${i%.*}.bmp
  done

else
  echo "Uso: $./t4 make|clean|test|plot|roc"
fi

