#!/bin/sh

bold=$(tput bold)
reset=$(tput sgr0)

if [ "$1" = "clean" ]; then
  echo "${bold}Cleaning...${reset}"
  rm -r build bin
  find . -not \( -path ./db -prune \) -type f -name '*.jpg' -exec rm -rf {} \;

elif [ "$1" = "make" ]; then
  mkdir -p build
  cd build
  cmake ..
  make

elif [ "$1" = "test" ]; then
  ./bin/t4 ./db/0024.jpg ./db/0024.bmp 
  
elif [ "$1" = "plot" ]; then
  python src/plot.py roc.csv

else
  echo "Uso: $./t4 make|clean|test|plot"
fi

