#!/bin/sh

bold=$(tput bold)
reset=$(tput sgr0)

if [ "$1" = "clean" ]; then
  echo "${bold}Cleaning...${reset}"
  rm -r build bin
  find . -not \( -path ./db -prune \) -type f -name '*.jpg' -exec rm -rf {} \;

elif [ "$1" = "make" ]; then
  mkdir -p build
  cd build
  cmake ..
  make

elif [ "$1" = "test" ]; then
  ./bin/t3 db/uch012a.jpg db/uch012b.jpg
  
else
  echo "Uso: $./t3 make|clean|test"
fi

